---
title: From me to you
hero_image: images/banner.png
description: Make your own interactive digital card to share with someone by giving
  them a web address
version: 4
listed: false
copyedit: true
last_tested: '2020-07-07'
steps:
- title: You will make
- title: The digital making process
- title: Your idea 💡
  completion:
  - engaged
- title: Plan your card 💌
- title: Make 🧱 and test 🔄
  completion:
  - internal
- title: Share 🗣️ and play
- title: Checklist ✅
- title: What next?
