title: Digital card
hero_image: images/banner.png
description: Make you own digital card which a user can interact with
version: 4
listed: false
copyedit: false
last_tested: "2020-07-07"
steps:
  - title: Introduction
  - title: The digital making process
  - title: Investigate digital cards
  - title: Choose a theme
  - title: How to...
  - title: Develop the interaction
  - title: Share your card
  - title: Reflect on your project
  - title: What next?


