title: interactive-card
hero_image: images/banner.png
description: interactive-card description
version: 4
listed: false
copyedit: false
last_tested: "2020-07-07"
steps:
  - title: Introduction
  - title: Step title
  - title: What next?
