---
title: From me to you
hero_image: images/banner.png
description: Make your own interactive digital card to share with someone by giving
  them a web address
version: 4
listed: false
copyedit: true
last_tested: '2020-07-07'
steps:
- title: Introduction
- title: The digital making process
- title: Get inspiration
  completion:
  - engaged
- title: Choose a theme
- title: Make
  completion:
  - internal
- title: Share
- title: Reflect
- title: What next?
